#!/bin/sh



trap "echo 'Do not do this'" HUP INT TERM TSTP QUIT


createCron(){
	echo "" 				> /home/tc/log

	echo "count=0;" 			> /home/tc/cron
	echo "while [ $""count -lt 60 ];"	>> /home/tc/cron
	echo "do"				>> /home/tc/cron
 	#echo "echo "tettt45t45t"" 		>> /home/tc/cron
	echo "pidof  Xvesa >/dev/null" 		>> /home/tc/cron
	echo "if [[ $""? -ne 0 ]];"		>> /home/tc/cron
	echo "then"				>> /home/tc/cron
        #echo "echo telnet >> /home/tc/log" 	>> /home/tc/cron
       	#echo "kill $(ps aux | grep "telnet" | awk '{print $1 }')"  >> /home/tc/cron
	#echo "kill $""(pidof telnet)"  		>> /home/tc/cron
	echo "pidof  telnet >/dev/null" 		>> /home/tc/cron

	echo "if [[ $""? -eq 0 ]];"		>> /home/tc/cron

	echo "then"				>> /home/tc/cron
	#echo "pkill -SIGINT telnet"  		>> /home/tc/cron
	#echo "pkill -INT telnet"  		>> /home/tc/cron
	echo "pkill -TERM telnet"  		>> /home/tc/cron
	echo "pkill sleep"  		>> /home/tc/cron
	#echo "kill $""(pidof telnet)"  		>> /home/tc/cron
	echo "echo -e '\r'"			>> /home/tc/cron
	echo "echo -e '\cc'"			>> /home/tc/cron

	echo "fi"				>> /home/tc/cron
	echo "exit"				>> /home/tc/cron
	echo "fi"				>> /home/tc/cron
	echo "sleep 10"				>> /home/tc/cron
	echo "done"				>> /home/tc/cron
}
createCron


staticIP() {
sudo pkill udhcpc
sudo ifconfig eth0 192.168.1.30 netmask 255.255.255.0 broadcast 192.168.1.255 up
sudo route add default gw 192.168.1.1
#sudo echo nameserver 8.8.8.8 > /etc/resolv.conf
#sudo echo nameserver 8.8.4.4 >> /etc/resolv.conf
}


getXSRmenuConf(){

read -p "Enter Username = " USER
read -p "Enter Password = " PASS
USER=user01
PASS=123456
XSRmenu $USER $PASS
}

#===========================================
read_options(){
	local choice
	read -p "Enter choice [ 1 - 3] " choice
	echo ""
	echo ""
	echo "---------------------"
	echo ""
	echo ""
	case $choice in
		1) getXSRmenuConf ;;
		2) RDPmenu ;;
		#*) exit;;
		#*) killall Xvesa;kill $(ps aux | grep "telnet" | awk '{print $1 }');;

	esac
}


show_menu() {
	clear
	echo "~~~~~~~~~~~~~~~~~~~~~"	
	echo " M A I N - M E N U"
	echo "~~~~~~~~~~~~~~~~~~~~~"
	echo "1. X Connection (The linux Server must have installed Telnet Server and the Lxpanel)"
	echo "2. RDP Connection"
	#echo "3. Exit"
	
}

#############################################################################

XSRmenu() {
USER=$1
PASS=$2
startx

sh cron &

aterm -e sh -c 'hsetroot -full /opt/backgrounds/win10.jpg;xmodmap /home/tc/en'

(echo " Welcome Please Wait...";echo -e "\r";sleep 10;echo $USER;echo -e "\r";sleep 3;echo $PASS; echo -e "\r";sleep 3;echo "export DISPLAY=$getLocIP:0";echo -e "\r";sleep 3;echo "lxpanel";echo -e "\r";sleep 555)|telnet $getSerIP >/dev/null &

}



RDPmenu() {
echo $getSerIP;read -p "Input RDP SERVER Username = " USER;read -p "Input RDP SERVER Password = " PASS;rdesktop -f -p $PASS -u $USER $getSerIP || exit 0
}







############################################
##############################################
###############################################





#=====================
#WAIT FOR NETWORK (I MUST EXAMINE)
#=====================
count=0
#echo -n Waiting for the network...
while [ "$count" -lt 60 ]; 
do
ifconfig eth0 | grep -q inet && break
sleep 1
count=$((count + 1))
echo -n .
done





VGA="800x600x16"
sudo sed -i -e 's/1024x768x32/'$VGA'/' /home/tc/.xsession
sudo sed -i -e 's/-nolisten/-ac/' /home/tc/.xsession
sudo sed -i -e 's/tcp//' /home/tc/.xsession


getSerIP=192.168.1.111
getLocIP=`ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
#USER=user01
#PASS=123456
#USER=user01
#PASS=123456

#aterm -e sh -c 'hsetroot -full /opt/backgrounds/win10.jpg;xmodmap /home/tc/en'





#show_menu
#read_options


#exit



#=============================================
count=0
while [ "$count" -lt 60 ]; 
do
show_menu
read_options
sleep 1
#count=$((count + 1))
done








