#!/bin/sh

getSerIP=192.168.1.111
getLocIP=`ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`

USER=user01
PASS=12345678

export getSerIP=$getSerIP;
export getLocIP=$getLocIP;
export USER=$USER
export PASS=$PASS

#=====================
#REMOTE DISPLAY & SCREEN ANALYSIS
#=====================
sudo sed -i -e 's/1024x768x32/'$VGA'/' /home/tc/.xsession
#su - tc -c 'sed -i -e 's/1024x768x32/'$VGA'/' /home/tc/.xsession'
sudo sed -i -e 's/-nolisten/-ac/' /home/tc/.xsession
sudo sed -i -e 's/tcp//' /home/tc/.xsession


startx

aterm -e sh -c `xmodmap /home/tc/gr;(echo "Welcome";echo -e "\r";sleep 10;echo $USER;echo -e "\r";sleep 3;echo "123456"; echo -e "\r";sleep 3;echo "ls";echo -e "\r";sleep 13;echo "export DISPLAY=$getLocIP:0";echo -e "\r";sleep 3;echo "gnome-panel";echo -e "\r";sleep 555)|telnet 192.168.1.1`


